phpCAS: CAS.php File Reference
CAS.php File Reference
Classes
class phpCAS
Namespaces
PhpCAS
Functions
gettmpdir ()
Variables
const PHPCAS_VERSION (!isset($_SERVER['REQUEST_URI']) &&isset($_SERVER['SCRIPT_NAME']) &&isset($_SERVER['QUERY_STRING'])) '1.4.0'
const CAS_VERSION_1_0 '1.0'
const CAS_VERSION_2_0 '2.0'
const CAS_VERSION_3_0 '3.0'
const SAML_VERSION_1_1 'S1'
const SAML_XML_HEADER '<?xml version="1.0" encoding="UTF-8"?>'
const SAML_SOAP_ENV '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/>'
const SAML_SOAP_BODY '<SOAP-ENV:Body>'
const SAMLP_REQUEST '<samlp:Request xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol" MajorVersion="1" MinorVersion="1" RequestID="_192.168.16.51.1024506224022" IssueInstant="2002-06-19T17:03:44.022Z">'
const SAMLP_REQUEST_CLOSE '</samlp:Request>'
const SAML_ASSERTION_ARTIFACT '<samlp:AssertionArtifact>'
const SAML_ASSERTION_ARTIFACT_CLOSE '</samlp:AssertionArtifact>'
const SAML_SOAP_BODY_CLOSE '</SOAP-ENV:Body>'
const SAML_SOAP_ENV_CLOSE '</SOAP-ENV:Envelope>'
const SAML_ATTRIBUTES 'SAMLATTRIBS'
const DEFAULT_ERROR 'Internal script failure'
const CAS_PGT_STORAGE_FILE_DEFAULT_PATH session_save_path()
const PHPCAS_SERVICE_OK 0
const PHPCAS_SERVICE_PT_NO_SERVER_RESPONSE 1
const PHPCAS_SERVICE_PT_BAD_SERVER_RESPONSE 2
const PHPCAS_SERVICE_PT_FAILURE 3
const PHPCAS_SERVICE_NOT_AVAILABLE 4
const PHPCAS_PROXIED_SERVICE_HTTP_GET 'CAS_ProxiedService_Http_Get'
const PHPCAS_PROXIED_SERVICE_HTTP_POST 'CAS_ProxiedService_Http_Post'
const PHPCAS_PROXIED_SERVICE_IMAP 'CAS_ProxiedService_Imap'
const PHPCAS_LANG_ENGLISH 'CAS_Languages_English'
const PHPCAS_LANG_FRENCH 'CAS_Languages_French'
const PHPCAS_LANG_GREEK 'CAS_Languages_Greek'
const PHPCAS_LANG_GERMAN 'CAS_Languages_German'
const PHPCAS_LANG_JAPANESE 'CAS_Languages_Japanese'
const PHPCAS_LANG_SPANISH 'CAS_Languages_Spanish'
const PHPCAS_LANG_CATALAN 'CAS_Languages_Catalan'
const PHPCAS_LANG_CHINESE_SIMPLIFIED 'CAS_Languages_ChineseSimplified'
const PHPCAS_LANG_GALEGO 'CAS_Languages_Galego'
const PHPCAS_LANG_PORTUGUESE 'CAS_Languages_Portuguese'
const PHPCAS_LANG_DEFAULT PHPCAS_LANG_ENGLISH
const DEFAULT_DEBUG_DIR gettmpdir()."/"
Variable Documentation
PHPCAS_VERSION
const PHPCAS_VERSION(!isset($_SERVER[ 'REQUEST_URI']) &&isset($_SERVER[ 'SCRIPT_NAME']) &&isset($_SERVER[ 'QUERY_STRING'])) '1.4.0'
phpCAS version. accessible for the user by phpCAS::getVersion().
Definition at line 60 of file CAS.php.
Referenced by phpCAS\getVersion(), phpCAS\setDebug(), and phpCAS\setLogger().