phpCAS: CAS_AuthenticationException Class Reference
CAS_AuthenticationException Class Reference
Public Member Functions
__construct ($client, $failure, $cas_url, $no_response, $bad_response=false, $cas_response='', $err_code=-1, $err_msg='')
Detailed Description
This interface defines methods that allow proxy-authenticated service handlers to interact with phpCAS.
Proxy service handlers must implement this interface as well as call phpCAS::initializeProxiedService($this) at some point in their implementation.
While not required, proxy-authenticated service handlers are encouraged to implement the CAS_ProxiedService_Testable interface to facilitate unit testing.
Definition at line 48 of file AuthenticationException.php.
Constructor & Destructor Documentation
__construct()
CAS_AuthenticationException::__construct ($client, $failure, $cas_url, $no_response, $bad_response = false, $cas_response = '', $err_code = -1, $err_msg = '')
This method is used to print the HTML output when the user was not authenticated.
Parameters
CAS_Client $client phpcas client
string $failure the failure that occured
string $cas_url the URL the CAS server was asked for
bool $no_response the response from the CAS server (other parameters are ignored if TRUE)
bool $bad_response bad response from the CAS server ($err_code and $err_msg ignored if TRUE)
string $cas_response the response of the CAS server
int $err_code the error code given by the CAS server
string $err_msg the error message given by the CAS server
Definition at line 68 of file AuthenticationException.php.
References $cas_url, $client, CAS_VERSION_1_0, CAS_VERSION_2_0, CAS_VERSION_3_0, phpCAS\trace(), phpCAS\traceBegin(), and phpCAS\traceExit().