phpCAS: HTML output
HTML output
User interface » Configuration
Functions
static phpCAS::setHTMLHeader ($header)
static phpCAS::setHTMLFooter ($footer)
Detailed Description
Function Documentation
setHTMLFooter()
static phpCAS::setHTMLFooter ($footer) static
This method sets the HTML footer used for all outputs.
Parameters
string $footer the HTML footer.
Returns
void
Examples:
example_html.php.
Definition at line 805 of file CAS.php.
References phpCAS\_validateClientExists(), and phpCAS\error().
setHTMLHeader()
static phpCAS::setHTMLHeader ($header) static
This method sets the HTML header used for all outputs.
Parameters
string $header the HTML header.
Returns
void
Examples:
example_html.php.
Definition at line 787 of file CAS.php.
References phpCAS\_validateClientExists(), and phpCAS\error().