phpCAS: CAS client features (CAS 2.0, Proxied service)
CAS client features (CAS 2.0, Proxied service)
Implementation
Functions
CAS_Client::getProxies ()
CAS_Client::_setProxies ($proxies)
CAS_Client::getAllowedProxyChains ()
Variables
CAS_Client::$_proxies = array()
CAS_Client::$_allowed_proxy_chains
Detailed Description
Function Documentation
_setProxies()
CAS_Client::_setProxies ($proxies) private
Set the Proxy array, probably from persistant storage.
Parameters
array $proxies An array of proxies
Returns
void private
Definition at line 3327 of file Client.php.
References CAS_Client\setNoClearTicketsFromUrl().
Referenced by CAS_Client\_wasPreviouslyAuthenticated().
getAllowedProxyChains()
CAS_Client::getAllowedProxyChains ()
Answer the CAS_ProxyChain_AllowedList object for this client.
Returns
CAS_ProxyChain_AllowedList
Definition at line 3354 of file Client.php.
References CAS_Client\$_allowed_proxy_chains.
Referenced by CAS_Client\validateCAS20().
getProxies()
CAS_Client::getProxies ()
Answer an array of proxies that are sitting in front of this application.
This method will only return a non-empty array if we have received and validated a Proxy Ticket.
Returns
array public
Definition at line 3314 of file Client.php.
References CAS_Client\$_proxies.
Variable Documentation
$_allowed_proxy_chains
CAS_Client::$_allowed_proxy_chains private
Definition at line 3347 of file Client.php.
Referenced by CAS_Client\getAllowedProxyChains().
$_proxies
CAS_Client::$_proxies = array() private
This array will store a list of proxies in front of this application. This property will only be populated if this script is being proxied rather than accessed directly.
It is set in CAS_Client::validateCAS20() and can be read by CAS_Client::getProxies()
private
Definition at line 3303 of file Client.php.
Referenced by CAS_Client\getProxies().