phpCAS: Callback from the CAS server
Callback from the CAS server
Implementation » CAS Proxy features (CAS 2.0, Proxy Granting Tickets)
Functions
CAS_Client::_setCallbackMode ($callback_mode)
CAS_Client::_isCallbackMode ()
CAS_Client::_setCallbackModeUsingPost ($callback_mode_using_post)
CAS_Client::_isCallbackModeUsingPost ()
CAS_Client::_getCallbackURL ()
CAS_Client::setCallbackURL ($url)
CAS_Client::_callback ()
CAS_Client::isXmlResponse ()
Variables
CAS_Client::$_callback_mode = false
CAS_Client::$_callback_mode_using_post = false
CAS_Client::$_callback_url
Detailed Description
Function Documentation
_callback()
CAS_Client::_callback () private
This method is called by CAS_Client::CAS_Client() when running in callback mode. It stores the PGT and its PGT Iou, prints its output and halts.
Returns
void
Definition at line 2587 of file Client.php.
References CAS_Client\_isCallbackModeUsingPost(), phpCAS\error(), CAS_Client\isXmlResponse(), CAS_Client\printHTMLFooter(), CAS_Client\printHTMLHeader(), phpCAS\trace(), phpCAS\traceBegin(), and phpCAS\traceExit().
Referenced by CAS_Client\_wasPreviouslyAuthenticated().
_getCallbackURL()
CAS_Client::_getCallbackURL () private
This method returns the URL that should be used for the PGT callback (in fact the URL of the current request without any CGI parameter, except if phpCAS::setFixedCallbackURL() was used).
Returns
string The callback URL
Definition at line 2548 of file Client.php.
References CAS_Client\$_callback_url, and CAS_Client\_getClientUrl().
Referenced by CAS_Client\validateCAS20().
_isCallbackMode()
CAS_Client::_isCallbackMode () private
This method returns true when the CAS client is running in callback mode, false otherwise.
Returns
bool A boolean.
Definition at line 2497 of file Client.php.
References CAS_Client\$_callback_mode.
Referenced by CAS_Client\__construct(), and CAS_Client\_wasPreviouslyAuthenticated().
_isCallbackModeUsingPost()
CAS_Client::_isCallbackModeUsingPost () private
This method returns true when the callback mode is using POST, false otherwise.
Returns
bool A boolean.
Definition at line 2527 of file Client.php.
References CAS_Client\$_callback_mode_using_post.
Referenced by CAS_Client\_callback().
_setCallbackMode()
CAS_Client::_setCallbackMode ($callback_mode) private
This method sets/unsets callback mode.
Parameters
bool $callback_mode true to set callback mode, false otherwise.
Returns
void
Definition at line 2486 of file Client.php.
Referenced by CAS_Client\__construct().
_setCallbackModeUsingPost()
CAS_Client::_setCallbackModeUsingPost ($callback_mode_using_post) private
This method sets/unsets usage of POST parameters in callback mode (default/false is GET parameters)
Parameters
bool $callback_mode_using_post true to use POST, false to use GET (default).
Returns
void
Definition at line 2517 of file Client.php.
Referenced by CAS_Client\__construct().
isXmlResponse()
CAS_Client::isXmlResponse () private
Check if application/xml or text/xml is pressent in HTTP_ACCEPT header values when return value is complex and contains attached q parameters. Example: HTTP_ACCEPT = text/html,application/xhtml+xml,application/xml;q=0.9
Returns
bool
Definition at line 2634 of file Client.php.
Referenced by CAS_Client\_callback().
setCallbackURL()
CAS_Client::setCallbackURL ($url)
This method sets the callback url.
Parameters
string $url url to set callback
Returns
string the callback url
Definition at line 2570 of file Client.php.
References CAS_Client\ensureIsProxy().
Variable Documentation
$_callback_mode
CAS_Client::$_callback_mode = false private
Definition at line 2477 of file Client.php.
Referenced by CAS_Client\_isCallbackMode().
$_callback_mode_using_post
CAS_Client::$_callback_mode_using_post = false private
Definition at line 2508 of file Client.php.
Referenced by CAS_Client\_isCallbackModeUsingPost().
$_callback_url
CAS_Client::$_callback_url private
the URL that should be used for the PGT callback (in fact the URL of the current request without any CGI parameter). Written and read by CAS_Client::_getCallbackURL().
Definition at line 2539 of file Client.php.
Referenced by CAS_Client\_getCallbackURL().