phpCAS: CAS SAML features (SAML 1.1)
CAS SAML features (SAML 1.1)
Implementation
Functions
CAS_Client::validateSA (&$validate_url, &$text_response, &$tree_response, $renew=false)
CAS_Client::_setSessionAttributes ($text_response)
Detailed Description
Function Documentation
_setSessionAttributes()
CAS_Client::_setSessionAttributes ($text_response) private
This method will parse the DOM and pull out the attributes from the SAML payload and put them into an array, then put the array into the session.
Parameters
string $text_response the SAML payload.
Returns
bool true when successfull and false if no attributes a found
Definition at line 2319 of file Client.php.
References phpCAS\trace(), phpCAS\traceBegin(), and phpCAS\traceEnd().
Referenced by CAS_Client\validateSA().
validateSA()
CAS_Client::validateSA (& $validate_url, & $text_response, & $tree_response, $renew = false)
This method is used to validate a SAML TICKET; halt on failure, and sets $validate_url, $text_reponse and $tree_response on success. These parameters are used later by CAS_Client::_validatePGT() for CAS proxies.
Parameters
string &$validate_url reference to the the URL of the request to the CAS server.
string &$text_response reference to the response of the CAS server, as is (XML text).
string &$tree_response reference to the response of the CAS server, as a DOM XML tree.
bool $renew true to force the authentication with the CAS server
Returns
bool true when successfull and issue a CAS_AuthenticationException and false on an error
Exceptions
CAS_AuthenticationException
Definition at line 2226 of file Client.php.
References CAS_Client\_renameSession(), CAS_Client\_setSessionAttributes(), CAS_Client\_setUser(), CAS_Client\getTicket(), phpCAS\trace(), and phpCAS\traceEnd().
Referenced by CAS_Client\isAuthenticated().